#!/bin/sh

# Add all admin ssh keys to v-* users
for user in $(grep ^v-slaves /etc/group | perl -F: -anlE 'my @u = split /,/, $F[3]; say "@u"'); do
    ssh=/home/$user/.ssh
    keys=$ssh/authorized_keys
    mkdir $ssh 2>/dev/null
    chown $user $ssh
    chmod 755 $ssh
    cat $(grep ^adm /etc/group \
        | perl -pe 's/.*://; s/,/ /g; s[(\S+)][/home/$1/.ssh/authorized_keys]g') \
        | sort \
        | uniq > $keys
    chmod 644 $keys
    chown $user $keys
done

