#!/usr/bin/env perl
use Modern::Perl;

given ($ARGV[0]) {
    when ("config") {
        print <<END;
graph_title APT: Installed packages
graph_args --base 1000 -l 0
graph_vlabel packages
graph_category Debian
graph_info The number of installed packages on the system (via dpkg)
count.label packages
count.type GAUGE
count.info The number of installed packages
END
    }
    default {
        my ($lines) = qx[dpkg -l | grep -c ^ii] =~ /^(\d+)/;
        say "count.value $lines";
    }
}
