#!/usr/bin/env perl
use 5.010;

given ($ARGV[0]) {
    when ("config") {
        print <<END;
graph_title downlode hotlinking victims
graph_args --base 1000 -l 0
graph_vlabel victims
graph_category apache
graph_info Hotlinking redirect victims at downlode.org, see http://bit.ly/9fjcgH
count.label victims
count.type GAUGE
count.info The number of victims we've sent a 302
END
    }
    default {
        my ($lines) = qx[cat /var/log/apache2/downlode.org/*.log | grep -c -h " 302 "] =~ /^(\d+)/;
        say "count.value $lines";
    }
}
