#!/usr/bin/env perl
use 5.010;
use Any::Moose;
use Hailo;

my $brain = $ENV{brain};
my $name  = $ENV{name} // $brain;

given ($ARGV[0]) {
    when ("config") {
        print <<"END";
graph_title Hailo statistics for $name
graph_args --base 1000 -l 0
graph_vlabel count
graph_category hailo
graph_info Statistics about the $name Hailo brain

tokens.label victims
tokens.type GAUGE
tokens.info The number of tokens in the brain

expressions.label victims
expressions.type GAUGE
expressions.info The number of expressions in the brain

prev_tokens.label victims
prev_tokens.type GAUGE
prev_tokens.info The number of prev_tokens in the brain

next_tokens.label victims
next_tokens.type GAUGE
next_tokens.info The number of next_tokens in the brain
END
    }
    default {
        my $hailo = Hailo->new(brain => $brain);
        my %stats;
        @stats{qw/tokens expressions prev_tokens next_tokens/} = $hailo->stats;
        say "$_.value $stats{$_}" for sort keys %stats;
    }
}
