#!/usr/bin/env perl
use 5.010;
use Any::Moose;
use Hailo;
use Time::HiRes qw/ gettimeofday tv_interval /;

my $brain = $ENV{brain};
my $name  = $ENV{name} // $brain;
my $times = $ENV{times} // 100;

given ($ARGV[0]) {
    when ("config") {
        print <<"END";
graph_title Hailo reply time for $name
graph_args --base 1000 -l 0
graph_vlabel millisecods
graph_category hailo
graph_info The time it takes the $name Hailo brain to make $times replies

time.label time
time.type GAUGE
time.info The time it took the brain to generate $times replies
END
    }
    default {
        my $hailo = Hailo->new(brain => $brain);
        # One reply to set up DB connections etc.
        $hailo->reply();

        my $start_time = [gettimeofday()];
        for (1 .. $times) {
            my $reply = $hailo->reply();
            die "Didn't get a reply" unless defined $reply;
        }
        my $elapsed = tv_interval($start_time);
        say "time.value ", int $elapsed * 1_000;
    }
}
