#!/usr/bin/env perl
use Modern::Perl;
use DBI;

my $user = $ENV{PGUSER};
my $pass = $ENV{PGPASSWORD};
my $host = $ENV{PGHOST} // 'localhost';
my $port = $ENV{PGPORT} // 5432;
my $dbnm = $ENV{PGDATABASE};

my $title = $ENV{graph_title} // 'The number of nodes, ways & relations in OSM';
my $desc = $ENV{graph_info}   // 'The number of nodes, ways & relations in the OpenStreetMap database';

my $dbh = DBI->connect("dbi:Pg:dbname=$dbnm;host=$host;port=$port", $user, $pass);

given ($ARGV[0]) {
    when ("config") {
        print <<END;
graph_title $title
graph_args --base 1000 -l 0
graph_vlabel primitives
graph_category OpenStreetMap
graph_info $desc
nodes.label Nodes
nodes.type GAUGE
ways.info The number of ways in the database
ways.label Ways
ways.type GAUGE
relations.info The number of relations in the database
relations.label Relations
relations.type GAUGE
relations.info The number of relations in the database
END
    }
    default {
        my ($nodes, $ways, $relations) = map {
            $dbh->selectall_arrayref("SELECT count(*) FROM current_$_")->[0][0]
        } qw(nodes ways relations);
        print <<END;
nodes.value $nodes
ways.value $ways
relations.value $relations
END
    }
}
