#!/home/v-perlbrew/perl5/perlbrew/bin/perl
use lib '/usr/share/perl5';
use 5.010;
use strict;
use lib '/etc/munin/our-plugins/lib';
use Munin::Cache::Tiny;

my $user = $ENV{PGUSER};
my $pass = $ENV{PGPASSWORD};
my $host = $ENV{PGHOST} // 'localhost';
my $port = $ENV{PGPORT} // 5432;
my $dbnm = $ENV{PGDATABASE};

my $what = $ENV{primitive};
my $What = ucfirst $what;
my $title = $ENV{graph_title} // "The number of $what in OSM";
my $desc = $ENV{graph_info}   // "The number of $what in the OpenStreetMap database";

given ($ARGV[0]) {
    when ("config") {
        print <<END;
graph_title $title
graph_args --base 1000 -l 0
graph_vlabel $what
graph_category OpenStreetMap
graph_info $desc
$what.info The number of $what in the database
$what.label $What
$what.type GAUGE
END
    }
    default {
        my $count = munin_cache_invalidated_on_file_change(
            $ENV{MUNIN_STATEFILE},
            '/var/www/osm.nix.is/latest/Iceland.osm.bz2',
            sub {
                require DBI;
                my $dbh = DBI->connect("dbi:Pg:dbname=$dbnm;host=$host;port=$port", $user, $pass);
                $dbh->selectall_arrayref("SELECT count(*) FROM current_$what")->[0][0];
            },
        );
        print <<END;
$what.value $count
END
    }
}
