#!/bin/sh
#
# A copy-paste of the homedirs script by Christian Kujau, hacked by Ævar Arnfjörð Bjarmason
# (c)2008, Christian Kujau <lists@nerdbynature.de>
# Inspired by the perl version from Philipp Gruber <pg@flupps.net>
#
# We still need a cronjob to update CACHEFILE once in a while, e.g.:
# */10 * * * * root [ -O /tmp/munin-apache_vhost.cache ] && find /var/log/apache2/ -maxdepth 1 -mindepth 1 -type d -exec du -sk {} \; | sort -n | sed 's/\/.*\///' > munin-apache_vhost.cache
#
CACHEFILE=/tmp/munin-apache_vhost.cache

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Apache vhost logs (in MB)'
	echo 'graph_args --base 1024 -l 1'
	echo 'graph_vlabel MBytes'
	echo 'graph_category apache'
	echo 'graph_info This graph shows the size of /var/log/apache/*/ directories'

	awk '!/lost\+found/ {gsub(/\//,"_"); gsub(/\./,"__"); print $2}' $CACHEFILE | sort | while read i; do
		echo "$i".label `echo "$i" | sed 's/__/./g' | sed 's/_/\//g'`
	done
	exit 0
fi	

awk '!/lost\+found/ {gsub(/\//,"_"); gsub(/\./,"__"); print $2".value "$1 * 1024 }' $CACHEFILE
